#!/usr/bin/python3
import os
import sys
import time
import logging
import calendar
import datetime

GERRIT_USER="sarah_wang"
GERRIT_HTTP_PSD="reHUWelKlKxPdzvEDOv/k+R3CEMJmGzqyiHbWMtgRw"
GERRIT_URL="pcbugit2.realsil.com.cn"
GERRIT_PORT="29418"

def convert_date_to_epoch(date, fmt):
    d = datetime.datetime.strptime (date, fmt)
    print(d.timetuple())
    # t = time.struct_time(tm_year=2019, tm_mon=1, tm_mday=2, tm_hour=16, tm_min=45, tm_sec=54, tm_wday=2, tm_yday=2, tm_isdst=-1)
    # t = time.struct_time(tm_year=2019, tm_mon=1, tm_mday=2, tm_hour=16, tm_min=45, tm_sec=54, tm_wday=2, tm_yday=2, tm_isdst=0)
    # ct = calendar.timegem(t)
    # print("ct=======")
    # print(ct)
    cal = calendar.timegm(d.timetuple())
    print("cal======")
    print(cal)
    tm = time.mktime(d.timetuple())
    print("tm=========")
    print(tm)


def get_proj_tag_time():
	date="Wed Jan 2 16:45:54 2019 +0800"
	date="Tue Jul 16 18:10:56 2019 +0800"
	date1=date.split(" ")
	tz=date1.pop()
	date=' '.join(date1)
	print(tz)
	print(date)
	t=time.strptime(date, "%a %b %d %H:%M:%S %Y")
	st = int(time.mktime(t))
	print(st)
	hh=int("%s%s" %(tz[1], tz[2]))
	mm=int("%s%s" %(tz[3], tz[4]))
	flag=tz[0]
	if flag == "+":
	    st = st - 60 * 60 * hh - 60 * mm
	elif flag == "-":
	    st = st + 60 * 60 *hh + 60 * mm
	print("%d %d %d" %(hh, mm, st))


def get_gerrit_patch_info(patch_id, user, http_psd):
	# curl -s -X GET --user sarah_wang:reHUWelKlKxPdzvEDOv/k+R3CEMJmGzqyiHbWMtgRw http://pcbugit2.realsil.com.cn:8080/a/changes/20391/?o=messages
	auth = " --user %s:%s " %(user, http_psd)
	host = "http://pcbugit2.realsil.com.cn:8080"
	cmd = "curl -s -X GET %s %s/a/changes/%s/?o=messages" % (auth, host, patch_id)
	count = 0
	find = 0
	resc = 0
	proj = ""
	status = ""
	merge_time = -1
	for line in os.popen(cmd).readlines():
		if resc == 3:
			break
		if '"project": "' in line:
			proj = line.split("\": \"")[1]
			proj = proj.split("\"")[0]
			print("proj: %s" %proj)
			resc = resc + 1
		if '"status": "' in line:
			status = line.split("\": \"")[1]
			status = status.split("\"")[0]
			print("status: %s" %status)
			resc = resc + 1
		if count == 7:
			print("line : %s" %line)
			#"date": "2019-06-27 07:30:11.341000000"
			date = line.split("\": \"")[1]
			date = date.split(".")[0]
			print("date: %s" %date)
			t=time.strptime(date, "%Y-%m-%d %H:%M:%S")
			merge_time = int(time.mktime(t))
			resc = resc + 1
		if '"tag": "autogenerated:gerrit:merged"' in line:
			print("find it")
			find = 1
		if find == 1:
			count = count + 1
	return [proj, status, merge_time]

def get_gerrit_patch_info1(patch_id):
    # curl -s -X GET --user sarah_wang:reHUWelKlKxPdzvEDOv/k+R3CEMJmGzqyiHbWMtgRw http://pcbugit2.realsil.com.cn:8080/a/changes/20391/?o=messages
    auth = " --user %s:%s " %(GERRIT_USER, GERRIT_HTTP_PSD)
    host = "http://%s:%s" %(GERRIT_URL, "8080")
    cmd = "curl -s -X GET \"Content-Type: application/json\" %s %s/a/changes/%s/?o=messages" % (auth, host, patch_id)
    count = 0
    find = 0
    resc = 0
    proj = ""
    status = ""
    merge_time = -1
    for line in os.popen(cmd).readlines():
        if resc == 3:
            break
        if '"project": "' in line and proj == "":
            logging.debug("line: %s" %line)
            proj = line.split("\": \"")[1]
            proj = proj.split("\"")[0]
            logging.info("proj: %s" %proj)
            resc = resc + 1
        if '"status": "' in line and status == "":
            logging.debug("line: %s" %line)
            status = line.split("\": \"")[1]
            status = status.split("\"")[0]
            logging.info("status: %s" %status)
            resc = resc + 1
        if count == 7:
            logging.info("gerrit message : %s" %line)
            #"date": "2019-06-27 07:30:11.341000000"
            date = line.split("\": \"")[1]
            date = date.split(".")[0]
            logging.info("date: %s" %date)
            t=time.strptime(date, "%Y-%m-%d %H:%M:%S")
            merge_time = int(time.mktime(t))
            resc = resc + 1
        if '"tag": "autogenerated:gerrit:merged"' in line:
            logging.debug("line: %s" %line)
            find = 1
        if find == 1:
            count = count + 1
    return [proj, status, merge_time]


if __name__ == '__main__':
    #level=logging.NOTSET/DEBUG/INFO/WARN/WARNING/ERROR/FATAL/CRITICAL
    logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    #logging.basicConfig(level=logging.WARN, format='%(levelname)s - %(message)s')
    logger = logging.getLogger(__name__)
    patch_id = "20391"
    patch_id = "20685"
    patch_id = "20664"
    user = "sarah_wang"
    http_psd = "reHUWelKlKxPdzvEDOv/k+R3CEMJmGzqyiHbWMtgRw"
    # res = ""
    # res = get_gerrit_patch_info1(patch_id)
    # print("res: ")
    # print(res)

    # print("=============")
    # get_proj_tag_time()
    date = "Wed Jan 2 16:45:54 2019 +0800"
    fmt = "%a %b %d %H:%M:%S %Y %z"
    convert_date_to_epoch(date, fmt)
